### ISSUE TITLE
Menu disappears on resize after narrow view menu opened

### ISSUE THREAD

**Issue by JacobStephens2** [davidvdev/portfolio-site#2]
If the viewport is narrow enough to display the burger menu, then the burger menu is opened and closed, then the viewport is resized to be wide, the menu items in the nav disappear.

You can see the issue in this screen recording:  [bit.ly/davidvdev-menu-disappear-on-resize](https://bit.ly/davidvdev-menu-disappear-on-resize).

**Comment by davidvdev** [comment]
Issue fixed with site rebuild.
